version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: cyberpizzaTest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - cyberpizza-db:/var/lib/postgres/data/
    ports:
      - "127.0.0.1:5432:5432"

    networks:
      - banknetwork

  cyberpizza:
    build: .
    image: cyberpizza:0.1.4.2
    container_name: cyberpizza
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cyberpizzaTest
    ports:
      - "8080:8080"
    depends_on:
      - db

    networks:
      - banknetwork

  kafka-1:
    image: bitnami/kafka:latest
    ports:
      - "127.0.0.1:9092:9092"
    hostname: kafka-1
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=E_G4tLB6QuSnaD313dtx6Q
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9090,EXTERNAL://kafka-1:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - A:/kafka-docker/docker-compose/volumes/server-1/:/bitnami/kafka
    networks:
      - banknetwork

  kafka-2:
    image: bitnami/kafka:latest
    hostname: kafka-2
    ports:
      - "127.0.0.1:9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=E_G4tLB6QuSnaD313dtx6Q
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9090,EXTERNAL://kafka-2:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - A:/kafka-docker/docker-compose/volumes/server-2/:/bitnami/kafka
    networks:
      - banknetwork


  kafka-3:
    image: bitnami/kafka:latest
    hostname: kafka-3
    ports:
      - "127.0.0.1:9096:9096"
    environment:
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=E_G4tLB6QuSnaD313dtx6Q
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9096
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-3:9090,EXTERNAL://kafka-3:9096
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - A:/kafka-docker/docker-compose/volumes/server-3/:/bitnami/kafka
    networks:
      - banknetwork


volumes:
  cyberpizza-db:

networks:
  banknetwork:
    external: true